name: breez_preferences
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.3.0
  shared_preferences: ^2.5.3
  shared_preference_app_group: ^1.1.1 # iOS Notification Service extension requirement to access shared preferences
