name: breez_sdk_liquid
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  app_group_directory:
    git:
      url: https://github.com/breez/app_group_directory
      ref: flutter-3.29
  service_injector:
    path: ../service_injector
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
  logging: ^1.3.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5